[package]
name = "ice_pub"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
iceoryx2 = "0.4.1"
tokio = { version = "1.40.0", features = ["full"] }
ice_shared = { path = "../ice_shared" }
clap = { version = "4.5.18", features = ["derive"] }
